#!/bin/sh
REPOS="$1"
TXN="$2"
# Make sure that the log message contains some text.
SVNLOOK=/usr/local/subversion/bin/svnlook

LOGMSG=`$SVNLOOK log -t "$TXN" "$REPOS" | grep "[a-zA-Z0-9]" | wc -c`
if [ $LOGMSG -lt 10 ];
then
  echo -e "please input more than 10  chars" 1>&2
  exit 1
fi
exit 0
